version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: gunominator
      MONGO_INITDB_ROOT_PASSWORD: r3l1s3#M3!28

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: gunominator
      ME_CONFIG_MONGODB_ADMINPASSWORD: r3l1s3#M3!28
      ME_CONFIG_MONGODB_URL: mongodb://gunominator:r3l1s3#M3!28@mongo:27017/
